# Code Generated by Sidekick is for learning and experimentation purposes only.
import time

import streamlit as st

ph = st.empty()

for i in range(101):
    with ph.container():
        st.metric("Progress", f"{i}%")
        st.progress(i)
    time.sleep(0.05)
